# This is a basic workflow to help you get started with Actions

name: Deploy Website
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.JS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12 
    - name: Install Surge
      run: npm install -g surge
    - name: Run Surge
      run: surge ./Bootcampnewapp.surge.sh --token ${{secrets.SURGE_TOKEN}} 
      
     
